// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\3\0\1\6\1\7\1\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\12\20\1\0\1\21"+
    "\1\22\1\23\1\24\2\0\4\25\1\26\25\25\1\27"+
    "\1\30\1\31\1\32\1\25\1\0\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\25\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\25\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\1\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\20\21\1\24"+
    "\1\1\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\3\0\1\40\1\41\1\42"+
    "\12\21\1\43\10\21\1\44\23\21\1\45\1\0\1\14"+
    "\1\0\1\14\22\21\1\46\3\21\1\47\2\21\1\50"+
    "\20\21\1\51\3\21\1\0\4\21\1\52\1\53\1\21"+
    "\1\54\5\21\1\55\1\56\4\21\1\57\4\21\1\60"+
    "\1\21\1\61\13\21\1\62\2\21\1\63\1\64\2\21"+
    "\1\0\3\21\1\65\1\66\1\67\1\70\4\21\1\71"+
    "\1\72\1\73\12\21\1\74\2\21\1\75\2\21\1\76"+
    "\2\21\1\77\1\0\1\21\1\100\3\21\1\101\3\21"+
    "\1\102\2\21\1\103\3\21\1\104\1\105\1\106\1\21"+
    "\1\107\1\21\1\110\2\21\1\0\1\21\1\111\1\21"+
    "\1\112\1\113\1\114\3\21\1\115\1\116\5\21\1\0"+
    "\1\117\1\120\4\21\1\121\2\21\1\122\1\0\2\21"+
    "\1\123\1\124\1\21\1\125\1\0\1\126\1\127\1\21"+
    "\1\0\1\21\1\0\1\130\13\0\1\131";

  private static int [] zzUnpackAction() {
    int [] result = new int[310];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\66\0\154\0\242\0\330\0\u010e\0\66"+
    "\0\66\0\u0144\0\u017a\0\66\0\u01b0\0\66\0\u01e6\0\u021c"+
    "\0\66\0\u0252\0\u0288\0\u02be\0\u02f4\0\66\0\66\0\u032a"+
    "\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da"+
    "\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\u0654\0\66"+
    "\0\u068a\0\66\0\66\0\66\0\66\0\66\0\66\0\66"+
    "\0\66\0\66\0\u06c0\0\66\0\u06f6\0\u072c\0\u0762\0\66"+
    "\0\66\0\66\0\u0798\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6"+
    "\0\u08dc\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\u0a56"+
    "\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u02f4\0\u0b9a\0\u0bd0"+
    "\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80"+
    "\0\u0db6\0\u0dec\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30"+
    "\0\u0f66\0\66\0\u0f9c\0\u0fd2\0\u1008\0\u1008\0\u103e\0\u1074"+
    "\0\u10aa\0\u10e0\0\u1116\0\u114c\0\u1182\0\u11b8\0\u11ee\0\u1224"+
    "\0\u125a\0\u1290\0\u12c6\0\u12fc\0\u1332\0\u1368\0\u139e\0\u13d4"+
    "\0\u02f4\0\u140a\0\u1440\0\u1476\0\u14ac\0\u14e2\0\u1518\0\u02f4"+
    "\0\u154e\0\u1584\0\u15ba\0\u15f0\0\u1626\0\u165c\0\u1692\0\u16c8"+
    "\0\u16fe\0\u1734\0\u176a\0\u17a0\0\u17d6\0\u180c\0\u1842\0\u1878"+
    "\0\u02f4\0\u18ae\0\u18e4\0\u191a\0\u1950\0\u1986\0\u19bc\0\u19f2"+
    "\0\u1a28\0\u02f4\0\u02f4\0\u1a5e\0\u02f4\0\u1a94\0\u1aca\0\u1b00"+
    "\0\u1b36\0\u1b6c\0\u02f4\0\u02f4\0\u1ba2\0\u1bd8\0\u1c0e\0\u1c44"+
    "\0\u02f4\0\u1c7a\0\u1cb0\0\u1ce6\0\u1d1c\0\u02f4\0\u1d52\0\u02f4"+
    "\0\u1d88\0\u1dbe\0\u1df4\0\u1e2a\0\u1e60\0\u1e96\0\u1ecc\0\u1f02"+
    "\0\u1f38\0\u1f6e\0\u1fa4\0\u02f4\0\u1fda\0\u2010\0\u02f4\0\u02f4"+
    "\0\u2046\0\u207c\0\u20b2\0\u20e8\0\u211e\0\u2154\0\u02f4\0\u02f4"+
    "\0\u02f4\0\u02f4\0\u218a\0\u21c0\0\u21f6\0\u222c\0\u02f4\0\u2262"+
    "\0\u02f4\0\u2298\0\u22ce\0\u2304\0\u233a\0\u2370\0\u23a6\0\u23dc"+
    "\0\u2412\0\u2448\0\u247e\0\u02f4\0\u24b4\0\u24ea\0\u02f4\0\u2520"+
    "\0\u2556\0\u258c\0\u25c2\0\u25f8\0\u02f4\0\u262e\0\u2664\0\u02f4"+
    "\0\u269a\0\u26d0\0\u2706\0\u02f4\0\u273c\0\u2772\0\u27a8\0\u02f4"+
    "\0\u27de\0\u2814\0\u02f4\0\u284a\0\u2880\0\u28b6\0\u02f4\0\u02f4"+
    "\0\u02f4\0\u28ec\0\u02f4\0\u2922\0\u02f4\0\u2958\0\u298e\0\u29c4"+
    "\0\u29fa\0\u02f4\0\u2a30\0\u02f4\0\u02f4\0\u02f4\0\u2a66\0\u2a9c"+
    "\0\u2ad2\0\u02f4\0\u02f4\0\u2b08\0\u2b3e\0\u2b74\0\u2baa\0\u2be0"+
    "\0\u2c16\0\u02f4\0\u02f4\0\u2c4c\0\u2c82\0\u2cb8\0\u2cee\0\u02f4"+
    "\0\u2d24\0\u2d5a\0\u02f4\0\u2d90\0\u2dc6\0\u2dfc\0\u02f4\0\u02f4"+
    "\0\u2e32\0\u02f4\0\u2e68\0\u02f4\0\u02f4\0\u2e9e\0\u2ed4\0\u2f0a"+
    "\0\u2f40\0\u02f4\0\u2f76\0\u2fac\0\u2fe2\0\u3018\0\u304e\0\u3084"+
    "\0\u30ba\0\u30f0\0\u3126\0\u315c\0\u3192\0\66";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[310];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\2\25\1\26\1\2\1\27"+
    "\1\2\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\25\1\37\1\25\1\40\1\25\1\41\1\25\1\42"+
    "\1\43\1\44\1\45\1\25\1\46\1\47\3\25\1\50"+
    "\1\51\1\52\70\0\1\3\106\0\1\53\65\0\1\54"+
    "\51\0\1\55\101\0\1\56\55\0\1\57\7\0\1\60"+
    "\57\0\1\61\5\0\1\62\61\0\1\63\3\0\1\64"+
    "\4\0\1\65\53\0\1\66\1\0\1\20\5\0\1\67"+
    "\10\0\1\67\51\0\1\70\65\0\1\71\65\0\1\72"+
    "\62\0\1\25\4\0\2\25\4\0\30\25\23\0\1\25"+
    "\4\0\2\25\4\0\1\25\1\73\16\25\1\74\7\25"+
    "\23\0\1\25\4\0\2\25\4\0\15\25\1\75\1\25"+
    "\1\76\6\25\1\77\1\25\23\0\1\25\4\0\2\25"+
    "\4\0\1\100\6\25\1\101\2\25\1\102\2\25\1\103"+
    "\12\25\23\0\1\25\4\0\2\25\4\0\4\25\1\104"+
    "\10\25\1\105\12\25\23\0\1\25\4\0\2\25\4\0"+
    "\12\25\1\106\1\25\1\107\10\25\1\110\2\25\23\0"+
    "\1\25\4\0\2\25\4\0\1\111\7\25\1\112\1\25"+
    "\1\113\2\25\1\114\12\25\23\0\1\25\4\0\2\25"+
    "\4\0\15\25\1\115\12\25\23\0\1\25\4\0\2\25"+
    "\4\0\5\25\1\116\5\25\1\117\1\120\13\25\23\0"+
    "\1\25\4\0\2\25\4\0\15\25\1\121\12\25\23\0"+
    "\1\25\4\0\2\25\4\0\1\122\3\25\1\123\15\25"+
    "\1\124\5\25\23\0\1\25\4\0\2\25\4\0\1\125"+
    "\16\25\1\126\2\25\1\127\5\25\23\0\1\25\4\0"+
    "\2\25\4\0\4\25\1\130\23\25\23\0\1\25\4\0"+
    "\2\25\4\0\7\25\1\131\11\25\1\132\1\133\1\25"+
    "\1\134\1\25\1\135\1\25\23\0\1\25\4\0\2\25"+
    "\4\0\7\25\1\136\7\25\1\137\10\25\23\0\1\25"+
    "\4\0\2\25\4\0\15\25\1\140\12\25\23\0\1\25"+
    "\4\0\2\25\4\0\7\25\1\141\20\25\67\0\1\142"+
    "\1\0\30\63\1\0\16\63\1\0\16\63\12\0\1\143"+
    "\73\0\1\144\60\0\1\145\1\0\1\145\2\0\1\146"+
    "\65\0\1\25\4\0\2\25\4\0\20\25\1\147\7\25"+
    "\23\0\1\25\4\0\2\25\4\0\20\25\1\150\7\25"+
    "\23\0\1\25\4\0\2\25\4\0\15\25\1\151\12\25"+
    "\23\0\1\25\4\0\2\25\4\0\4\25\1\152\23\25"+
    "\23\0\1\25\4\0\2\25\4\0\21\25\1\153\6\25"+
    "\23\0\1\25\4\0\2\25\4\0\20\25\1\154\1\155"+
    "\6\25\23\0\1\25\4\0\2\25\4\0\1\156\27\25"+
    "\23\0\1\25\4\0\2\25\4\0\1\157\27\25\23\0"+
    "\1\25\4\0\2\25\4\0\14\25\1\160\13\25\23\0"+
    "\1\25\4\0\2\25\4\0\5\25\1\161\22\25\23\0"+
    "\1\25\4\0\2\25\4\0\22\25\1\162\5\25\23\0"+
    "\1\25\4\0\2\25\4\0\20\25\1\163\7\25\23\0"+
    "\1\25\4\0\2\25\4\0\22\25\1\164\5\25\23\0"+
    "\1\25\4\0\2\25\4\0\21\25\1\165\6\25\23\0"+
    "\1\25\4\0\2\25\4\0\12\25\1\166\15\25\23\0"+
    "\1\25\4\0\2\25\4\0\14\25\1\167\13\25\23\0"+
    "\1\25\4\0\2\25\4\0\15\25\1\170\12\25\23\0"+
    "\1\25\4\0\2\25\4\0\17\25\1\171\10\25\23\0"+
    "\1\25\4\0\2\25\4\0\21\25\1\172\6\25\23\0"+
    "\1\25\4\0\2\25\4\0\16\25\1\173\11\25\23\0"+
    "\1\25\4\0\2\25\4\0\20\25\1\174\1\175\6\25"+
    "\23\0\1\25\4\0\2\25\4\0\14\25\1\176\13\25"+
    "\23\0\1\25\4\0\2\25\4\0\21\25\1\177\6\25"+
    "\23\0\1\25\4\0\2\25\4\0\24\25\1\200\3\25"+
    "\23\0\1\25\4\0\2\25\4\0\12\25\1\201\15\25"+
    "\23\0\1\25\4\0\2\25\4\0\2\25\1\202\25\25"+
    "\23\0\1\25\4\0\2\25\4\0\10\25\1\203\4\25"+
    "\1\204\12\25\23\0\1\25\4\0\2\25\4\0\1\25"+
    "\1\205\26\25\23\0\1\25\4\0\2\25\4\0\21\25"+
    "\1\206\6\25\23\0\1\25\4\0\2\25\4\0\15\25"+
    "\1\207\12\25\23\0\1\25\4\0\2\25\4\0\1\210"+
    "\16\25\1\211\10\25\23\0\1\25\4\0\2\25\4\0"+
    "\16\25\1\212\11\25\23\0\1\25\4\0\2\25\4\0"+
    "\10\25\1\213\17\25\23\0\1\25\4\0\2\25\4\0"+
    "\14\25\1\214\13\25\23\0\1\25\4\0\2\25\4\0"+
    "\10\25\1\215\6\25\1\216\10\25\23\0\1\25\4\0"+
    "\2\25\4\0\1\217\21\25\1\220\3\25\1\221\1\25"+
    "\23\0\1\25\4\0\2\25\4\0\10\25\1\222\1\25"+
    "\1\223\15\25\23\0\1\25\4\0\2\25\4\0\10\25"+
    "\1\224\17\25\13\0\1\225\75\0\1\144\5\0\1\67"+
    "\10\0\1\67\46\0\1\146\65\0\1\25\4\0\2\25"+
    "\4\0\21\25\1\226\6\25\23\0\1\25\4\0\2\25"+
    "\4\0\4\25\1\227\23\25\23\0\1\25\4\0\2\25"+
    "\4\0\12\25\1\230\15\25\23\0\1\25\4\0\2\25"+
    "\4\0\1\231\27\25\23\0\1\25\4\0\2\25\4\0"+
    "\4\25\1\232\23\25\23\0\1\25\4\0\2\25\4\0"+
    "\4\25\1\233\23\25\23\0\1\25\4\0\2\25\4\0"+
    "\2\25\1\234\25\25\23\0\1\25\4\0\2\25\4\0"+
    "\17\25\1\235\10\25\23\0\1\25\4\0\2\25\4\0"+
    "\20\25\1\236\7\25\23\0\1\25\4\0\2\25\4\0"+
    "\20\25\1\237\1\240\6\25\23\0\1\25\4\0\2\25"+
    "\4\0\1\241\27\25\23\0\1\25\4\0\2\25\4\0"+
    "\1\25\1\242\26\25\23\0\1\25\4\0\2\25\4\0"+
    "\4\25\1\243\23\25\23\0\1\25\4\0\2\25\4\0"+
    "\13\25\1\244\14\25\23\0\1\25\4\0\2\25\4\0"+
    "\4\25\1\245\23\25\23\0\1\25\4\0\2\25\4\0"+
    "\20\25\1\246\7\25\23\0\1\25\4\0\2\25\4\0"+
    "\1\247\27\25\23\0\1\25\4\0\2\25\4\0\1\250"+
    "\27\25\23\0\1\25\4\0\2\25\4\0\15\25\1\251"+
    "\12\25\23\0\1\25\4\0\2\25\4\0\12\25\1\252"+
    "\2\25\1\253\12\25\23\0\1\25\4\0\2\25\4\0"+
    "\21\25\1\254\6\25\23\0\1\25\4\0\2\25\4\0"+
    "\4\25\1\255\23\25\23\0\1\25\4\0\2\25\4\0"+
    "\6\25\1\256\21\25\23\0\1\25\4\0\2\25\4\0"+
    "\10\25\1\257\17\25\23\0\1\25\4\0\2\25\4\0"+
    "\12\25\1\260\15\25\23\0\1\25\4\0\2\25\4\0"+
    "\11\25\1\261\16\25\23\0\1\25\4\0\2\25\4\0"+
    "\23\25\1\262\4\25\23\0\1\25\4\0\2\25\4\0"+
    "\21\25\1\263\6\25\23\0\1\25\4\0\2\25\4\0"+
    "\12\25\1\264\15\25\23\0\1\25\4\0\2\25\4\0"+
    "\22\25\1\265\5\25\23\0\1\25\4\0\2\25\4\0"+
    "\17\25\1\266\10\25\23\0\1\25\4\0\2\25\4\0"+
    "\21\25\1\267\6\25\23\0\1\25\4\0\2\25\4\0"+
    "\10\25\1\270\17\25\23\0\1\25\4\0\2\25\4\0"+
    "\4\25\1\271\23\25\23\0\1\25\4\0\2\25\4\0"+
    "\21\25\1\272\6\25\23\0\1\25\4\0\2\25\4\0"+
    "\2\25\1\273\25\25\23\0\1\25\4\0\2\25\4\0"+
    "\20\25\1\274\7\25\23\0\1\25\4\0\2\25\4\0"+
    "\15\25\1\275\12\25\23\0\1\25\4\0\2\25\4\0"+
    "\14\25\1\276\13\25\23\0\1\25\4\0\2\25\4\0"+
    "\4\25\1\277\23\25\23\0\1\25\4\0\2\25\4\0"+
    "\3\25\1\300\24\25\23\0\1\25\4\0\2\25\4\0"+
    "\1\301\27\25\23\0\1\25\4\0\2\25\4\0\12\25"+
    "\1\302\15\25\32\0\1\303\56\0\1\25\4\0\2\25"+
    "\4\0\17\25\1\304\10\25\23\0\1\25\4\0\2\25"+
    "\4\0\17\25\1\305\10\25\23\0\1\25\4\0\2\25"+
    "\4\0\4\25\1\306\23\25\23\0\1\25\4\0\2\25"+
    "\4\0\11\25\1\307\16\25\23\0\1\25\4\0\2\25"+
    "\4\0\7\25\1\310\20\25\23\0\1\25\4\0\2\25"+
    "\4\0\20\25\1\311\7\25\23\0\1\25\4\0\2\25"+
    "\4\0\21\25\1\312\6\25\23\0\1\25\4\0\2\25"+
    "\4\0\10\25\1\313\17\25\23\0\1\25\4\0\2\25"+
    "\4\0\22\25\1\314\5\25\23\0\1\25\4\0\2\25"+
    "\4\0\12\25\1\315\15\25\23\0\1\25\4\0\2\25"+
    "\4\0\14\25\1\316\13\25\23\0\1\25\4\0\2\25"+
    "\4\0\4\25\1\317\23\25\23\0\1\25\4\0\2\25"+
    "\4\0\12\25\1\320\15\25\23\0\1\25\4\0\2\25"+
    "\4\0\21\25\1\321\6\25\23\0\1\25\4\0\2\25"+
    "\4\0\4\25\1\322\23\25\23\0\1\25\4\0\2\25"+
    "\4\0\17\25\1\323\10\25\23\0\1\25\4\0\2\25"+
    "\4\0\1\324\27\25\23\0\1\25\4\0\2\25\4\0"+
    "\17\25\1\325\10\25\23\0\1\25\4\0\2\25\4\0"+
    "\23\25\1\326\4\25\23\0\1\25\4\0\2\25\4\0"+
    "\1\327\27\25\23\0\1\25\4\0\2\25\4\0\1\330"+
    "\27\25\23\0\1\25\4\0\2\25\4\0\4\25\1\331"+
    "\23\25\23\0\1\25\4\0\2\25\4\0\10\25\1\332"+
    "\17\25\23\0\1\25\4\0\2\25\4\0\17\25\1\333"+
    "\10\25\23\0\1\25\4\0\2\25\4\0\21\25\1\334"+
    "\6\25\23\0\1\25\4\0\2\25\4\0\10\25\1\335"+
    "\17\25\23\0\1\25\4\0\2\25\4\0\2\25\1\336"+
    "\25\25\23\0\1\25\4\0\2\25\4\0\17\25\1\337"+
    "\10\25\23\0\1\25\4\0\2\25\4\0\2\25\1\340"+
    "\25\25\23\0\1\25\4\0\2\25\4\0\7\25\1\341"+
    "\20\25\23\0\1\25\4\0\2\25\4\0\24\25\1\342"+
    "\3\25\23\0\1\25\4\0\2\25\4\0\20\25\1\343"+
    "\7\25\23\0\1\25\4\0\2\25\4\0\21\25\1\344"+
    "\6\25\23\0\1\25\4\0\2\25\4\0\4\25\1\345"+
    "\23\25\35\0\1\346\53\0\1\25\4\0\2\25\4\0"+
    "\1\347\27\25\23\0\1\25\4\0\2\25\4\0\21\25"+
    "\1\350\6\25\23\0\1\25\4\0\2\25\4\0\1\351"+
    "\27\25\23\0\1\25\4\0\2\25\4\0\14\25\1\352"+
    "\13\25\23\0\1\25\4\0\2\25\4\0\12\25\1\353"+
    "\15\25\23\0\1\25\4\0\2\25\4\0\4\25\1\354"+
    "\23\25\23\0\1\25\4\0\2\25\4\0\3\25\1\355"+
    "\24\25\23\0\1\25\4\0\2\25\4\0\12\25\1\356"+
    "\15\25\23\0\1\25\4\0\2\25\4\0\13\25\1\357"+
    "\14\25\23\0\1\25\4\0\2\25\4\0\21\25\1\360"+
    "\6\25\23\0\1\25\4\0\2\25\4\0\14\25\1\361"+
    "\13\25\23\0\1\25\4\0\2\25\4\0\5\25\1\362"+
    "\22\25\23\0\1\25\4\0\2\25\4\0\4\25\1\363"+
    "\23\25\23\0\1\25\4\0\2\25\4\0\6\25\1\364"+
    "\21\25\23\0\1\25\4\0\2\25\4\0\21\25\1\365"+
    "\6\25\23\0\1\25\4\0\2\25\4\0\2\25\1\366"+
    "\25\25\23\0\1\25\4\0\2\25\4\0\2\25\1\367"+
    "\25\25\23\0\1\25\4\0\2\25\4\0\14\25\1\370"+
    "\13\25\23\0\1\25\4\0\2\25\4\0\2\25\1\371"+
    "\25\25\23\0\1\25\4\0\2\25\4\0\21\25\1\372"+
    "\6\25\23\0\1\25\4\0\2\25\4\0\7\25\1\373"+
    "\20\25\23\0\1\25\4\0\2\25\4\0\17\25\1\374"+
    "\10\25\23\0\1\25\4\0\2\25\4\0\20\25\1\375"+
    "\7\25\23\0\1\25\4\0\2\25\4\0\10\25\1\376"+
    "\17\25\23\0\1\25\4\0\2\25\4\0\10\25\1\377"+
    "\17\25\15\0\1\u0100\73\0\1\25\4\0\2\25\4\0"+
    "\2\25\1\u0101\25\25\23\0\1\25\4\0\2\25\4\0"+
    "\14\25\1\u0102\13\25\23\0\1\25\4\0\2\25\4\0"+
    "\22\25\1\u0103\5\25\23\0\1\25\4\0\2\25\4\0"+
    "\21\25\1\u0104\6\25\23\0\1\25\4\0\2\25\4\0"+
    "\20\25\1\u0105\7\25\23\0\1\25\4\0\2\25\4\0"+
    "\26\25\1\u0106\1\25\23\0\1\25\4\0\2\25\4\0"+
    "\4\25\1\u0107\23\25\23\0\1\25\4\0\2\25\4\0"+
    "\2\25\1\u0108\25\25\23\0\1\25\4\0\2\25\4\0"+
    "\1\u0109\27\25\23\0\1\25\4\0\2\25\4\0\4\25"+
    "\1\u010a\23\25\23\0\1\25\4\0\2\25\4\0\4\25"+
    "\1\u010b\23\25\23\0\1\25\4\0\2\25\4\0\21\25"+
    "\1\u010c\6\25\23\0\1\25\4\0\2\25\4\0\5\25"+
    "\1\u010d\22\25\23\0\1\25\4\0\2\25\4\0\15\25"+
    "\1\u010e\12\25\23\0\1\25\4\0\2\25\4\0\4\25"+
    "\1\u010f\23\25\23\0\1\25\4\0\2\25\4\0\12\25"+
    "\1\u0110\15\25\34\0\1\u0111\54\0\1\25\4\0\2\25"+
    "\4\0\21\25\1\u0112\6\25\23\0\1\25\4\0\2\25"+
    "\4\0\4\25\1\u0113\23\25\23\0\1\25\4\0\2\25"+
    "\4\0\14\25\1\u0114\13\25\23\0\1\25\4\0\2\25"+
    "\4\0\4\25\1\u0115\23\25\23\0\1\25\4\0\2\25"+
    "\4\0\2\25\1\u0116\25\25\23\0\1\25\4\0\2\25"+
    "\4\0\4\25\1\u0117\23\25\23\0\1\25\4\0\2\25"+
    "\4\0\16\25\1\u0118\11\25\23\0\1\25\4\0\2\25"+
    "\4\0\14\25\1\u0119\13\25\23\0\1\25\4\0\2\25"+
    "\4\0\14\25\1\u011a\13\25\23\0\1\25\4\0\2\25"+
    "\4\0\4\25\1\u011b\23\25\67\0\1\u011c\21\0\1\25"+
    "\4\0\2\25\4\0\21\25\1\u011d\6\25\23\0\1\25"+
    "\4\0\2\25\4\0\15\25\1\u011e\12\25\23\0\1\25"+
    "\4\0\2\25\4\0\4\25\1\u011f\23\25\23\0\1\25"+
    "\4\0\2\25\4\0\3\25\1\u0120\24\25\23\0\1\25"+
    "\4\0\2\25\4\0\10\25\1\u0121\17\25\23\0\1\25"+
    "\4\0\2\25\4\0\21\25\1\u0122\6\25\13\0\1\u0123"+
    "\75\0\1\25\4\0\2\25\4\0\20\25\1\u0124\7\25"+
    "\23\0\1\25\4\0\2\25\4\0\5\25\1\u0125\22\25"+
    "\23\0\1\25\4\0\2\25\4\0\27\25\1\u0126\33\0"+
    "\1\u0127\55\0\1\25\4\0\2\25\4\0\4\25\1\u0128"+
    "\23\25\15\0\1\u0129\73\0\1\25\4\0\2\25\4\0"+
    "\3\25\1\u012a\24\25\16\0\1\u012b\101\0\1\u012c\70\0"+
    "\1\u012d\52\0\1\u012e\77\0\1\u012f\45\0\1\u0130\65\0"+
    "\1\u0131\66\0\1\u0132\103\0\1\u0133\47\0\1\u0134\66\0"+
    "\1\u0135\71\0\1\u0136\46\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12744];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\2\11\2\1\1\11\1\1\1\11"+
    "\2\1\1\11\4\1\2\11\20\1\1\11\1\1\11\11"+
    "\1\1\1\11\3\0\3\11\47\1\1\11\1\0\1\1"+
    "\1\0\57\1\1\0\55\1\1\0\42\1\1\0\31\1"+
    "\1\0\20\1\1\0\12\1\1\0\6\1\1\0\3\1"+
    "\1\0\1\1\1\0\1\1\13\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[310];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
            // fall through
          case 90: break;
          case 2:
            { /* Ignorar */
            }
            // fall through
          case 91: break;
          case 3:
            { return token(yytext(), "OPERADOR_ARITMETICO:MODULO", yyline, yycolumn);
            }
            // fall through
          case 92: break;
          case 4:
            { return token(yytext(), "DELIMITADOR:PARENTESIS_APERTURA", yyline, yycolumn);
            }
            // fall through
          case 93: break;
          case 5:
            { return token(yytext(), "DELIMITADOR:PARENTESIS_CIERRE", yyline, yycolumn);
            }
            // fall through
          case 94: break;
          case 6:
            { return token(yytext(), "OPERADOR_ARITMETICO:MULTIPLICACION", yyline, yycolumn);
            }
            // fall through
          case 95: break;
          case 7:
            { return token(yytext(), "OPERADOR_ARITMETICO:SUMA", yyline, yycolumn);
            }
            // fall through
          case 96: break;
          case 8:
            { return token(yytext(), "DELIMITADOR:COMA", yyline, yycolumn);
            }
            // fall through
          case 97: break;
          case 9:
            { return token(yytext(), "OPERADOR_ARITMETICO:RESTA", yyline, yycolumn);
            }
            // fall through
          case 98: break;
          case 10:
            { return token(yytext(), "DELIMITADOR:PUNTO", yyline, yycolumn);
            }
            // fall through
          case 99: break;
          case 11:
            { return token(yytext(), "OPERADOR_ARITMETICO:DIVISION", yyline, yycolumn);
            }
            // fall through
          case 100: break;
          case 12:
            { return token(yytext(), "NUMERO", yyline, yycolumn);
            }
            // fall through
          case 101: break;
          case 13:
            { return token(yytext(), "DELIMITADOR:PUNTO_COMA", yyline, yycolumn);
            }
            // fall through
          case 102: break;
          case 14:
            { return token(yytext(), "OPERADOR_RELACIONAL:MENOR", yyline, yycolumn);
            }
            // fall through
          case 103: break;
          case 15:
            { return token(yytext(), "OPERADOR_ASIGNACION:ASIGNACION_SIMPLE", yyline, yycolumn);
            }
            // fall through
          case 104: break;
          case 16:
            { return token(yytext(), "OPERADOR_RELACIONAL:MAYOR", yyline, yycolumn);
            }
            // fall through
          case 105: break;
          case 17:
            { return token(yytext(), "IDENTIFICADOR", yyline, yycolumn);
            }
            // fall through
          case 106: break;
          case 18:
            { return token(yytext(), "DELIMITADOR:CORCHETE_APERTURA", yyline, yycolumn);
            }
            // fall through
          case 107: break;
          case 19:
            { return token(yytext(), "DELIMITADOR:CORCHETE_CIERRE", yyline, yycolumn);
            }
            // fall through
          case 108: break;
          case 20:
            { return token(yytext(), "DELIMITADOR:LLAVE_APERTURA", yyline, yycolumn);
            }
            // fall through
          case 109: break;
          case 21:
            { return token(yytext(), "DELIMITADOR:LLAVE_CIERRE", yyline, yycolumn);
            }
            // fall through
          case 110: break;
          case 22:
            { return token(yytext(), "OPERADOR_RELACIONAL:DIFERENTE", yyline, yycolumn);
            }
            // fall through
          case 111: break;
          case 23:
            { return token(yytext(), "OPERADOR_ASIGNACION:ASIGNACION_MODULO", yyline, yycolumn);
            }
            // fall through
          case 112: break;
          case 24:
            { return token(yytext(), "OPERADOR_LOGICO:AND", yyline, yycolumn);
            }
            // fall through
          case 113: break;
          case 25:
            { return token(yytext(), "OPERADOR_ASIGNACION:ASIGNACION_MULTIPLICACION", yyline, yycolumn);
            }
            // fall through
          case 114: break;
          case 26:
            { return token(yytext(), "OPERADOR_ARITMETICO:INCREMENTO", yyline, yycolumn);
            }
            // fall through
          case 115: break;
          case 27:
            { return token(yytext(), "OPERADOR_ASIGNACION:ASIGNACION_SUMA", yyline, yycolumn);
            }
            // fall through
          case 116: break;
          case 28:
            { return token(yytext(), "OPERADOR_ARITMETICO:DECREMENTO", yyline, yycolumn);
            }
            // fall through
          case 117: break;
          case 29:
            { return token(yytext(), "OPERADOR_ASIGNACION:ASIGNACION_RESTA", yyline, yycolumn);
            }
            // fall through
          case 118: break;
          case 30:
            { /* Ignorar comentarios de una línea */
            }
            // fall through
          case 119: break;
          case 31:
            { return token(yytext(), "OPERADOR_ASIGNACION:ASIGNACION_DIVISION", yyline, yycolumn);
            }
            // fall through
          case 120: break;
          case 32:
            { return token(yytext(), "OPERADOR_RELACIONAL:MENOR_IGUAL", yyline, yycolumn);
            }
            // fall through
          case 121: break;
          case 33:
            { return token(yytext(), "OPERADOR_RELACIONAL:IGUAL", yyline, yycolumn);
            }
            // fall through
          case 122: break;
          case 34:
            { return token(yytext(), "OPERADOR_RELACIONAL:MAYOR_IGUAL", yyline, yycolumn);
            }
            // fall through
          case 123: break;
          case 35:
            { return token(yytext(), "PALABRA_RESERVADA:DO", yyline, yycolumn);
            }
            // fall through
          case 124: break;
          case 36:
            { return token(yytext(), "PALABRA_RESERVADA:IF", yyline, yycolumn);
            }
            // fall through
          case 125: break;
          case 37:
            { return token(yytext(), "OPERADOR_LOGICO:OR", yyline, yycolumn);
            }
            // fall through
          case 126: break;
          case 38:
            { return token(yytext(), "PALABRA_RESERVADA:FOR", yyline, yycolumn);
            }
            // fall through
          case 127: break;
          case 39:
            { return token(yytext(), "PALABRA_RESERVADA:INT", yyline, yycolumn);
            }
            // fall through
          case 128: break;
          case 40:
            { return token(yytext(), "PALABRA_RESERVADA:NEW", yyline, yycolumn);
            }
            // fall through
          case 129: break;
          case 41:
            { return token(yytext(), "PALABRA_RESERVADA:TRY", yyline, yycolumn);
            }
            // fall through
          case 130: break;
          case 42:
            { return token(yytext(), "PALABRA_RESERVADA:BYTE", yyline, yycolumn);
            }
            // fall through
          case 131: break;
          case 43:
            { return token(yytext(), "PALABRA_RESERVADA:CASE", yyline, yycolumn);
            }
            // fall through
          case 132: break;
          case 44:
            { return token(yytext(), "PALABRA_RESERVADA:CHAR", yyline, yycolumn);
            }
            // fall through
          case 133: break;
          case 45:
            { return token(yytext(), "PALABRA_RESERVADA:ELSE", yyline, yycolumn);
            }
            // fall through
          case 134: break;
          case 46:
            { return token(yytext(), "PALABRA_RESERVADA:ENUM", yyline, yycolumn);
            }
            // fall through
          case 135: break;
          case 47:
            { return token(yytext(), "PALABRA_RESERVADA:GOTO", yyline, yycolumn);
            }
            // fall through
          case 136: break;
          case 48:
            { return token(yytext(), "PALABRA_RESERVADA:LONG", yyline, yycolumn);
            }
            // fall through
          case 137: break;
          case 49:
            { return token(yytext(), "PALABRA_RESERVADA:NULL", yyline, yycolumn);
            }
            // fall through
          case 138: break;
          case 50:
            { return token(yytext(), "PALABRA_RESERVADA:THIS", yyline, yycolumn);
            }
            // fall through
          case 139: break;
          case 51:
            { return token(yytext(), "PALABRA_RESERVADA:TRUE", yyline, yycolumn);
            }
            // fall through
          case 140: break;
          case 52:
            { return token(yytext(), "PALABRA_RESERVADA:VOID", yyline, yycolumn);
            }
            // fall through
          case 141: break;
          case 53:
            { return token(yytext(), "PALABRA_RESERVADA:BREAK", yyline, yycolumn);
            }
            // fall through
          case 142: break;
          case 54:
            { return token(yytext(), "PALABRA_RESERVADA:CATCH", yyline, yycolumn);
            }
            // fall through
          case 143: break;
          case 55:
            { return token(yytext(), "PALABRA_RESERVADA:CLASS", yyline, yycolumn);
            }
            // fall through
          case 144: break;
          case 56:
            { return token(yytext(), "PALABRA_RESERVADA:CONST", yyline, yycolumn);
            }
            // fall through
          case 145: break;
          case 57:
            { return token(yytext(), "PALABRA_RESERVADA:FALSE", yyline, yycolumn);
            }
            // fall through
          case 146: break;
          case 58:
            { return token(yytext(), "PALABRA_RESERVADA:FINAL", yyline, yycolumn);
            }
            // fall through
          case 147: break;
          case 59:
            { return token(yytext(), "PALABRA_RESERVADA:FLOAT", yyline, yycolumn);
            }
            // fall through
          case 148: break;
          case 60:
            { return token(yytext(), "PALABRA_RESERVADA:SHORT", yyline, yycolumn);
            }
            // fall through
          case 149: break;
          case 61:
            { return token(yytext(), "PALABRA_RESERVADA:SUPER", yyline, yycolumn);
            }
            // fall through
          case 150: break;
          case 62:
            { return token(yytext(), "PALABRA_RESERVADA:THROW", yyline, yycolumn);
            }
            // fall through
          case 151: break;
          case 63:
            { return token(yytext(), "PALABRA_RESERVADA:WHILE", yyline, yycolumn);
            }
            // fall through
          case 152: break;
          case 64:
            { return token(yytext(), "PALABRA_RESERVADA:ASSERT", yyline, yycolumn);
            }
            // fall through
          case 153: break;
          case 65:
            { return token(yytext(), "PALABRA_RESERVADA:DOUBLE", yyline, yycolumn);
            }
            // fall through
          case 154: break;
          case 66:
            { return token(yytext(), "PALABRA_RESERVADA:IMPORT", yyline, yycolumn);
            }
            // fall through
          case 155: break;
          case 67:
            { return token(yytext(), "PALABRA_RESERVADA:NATIVE", yyline, yycolumn);
            }
            // fall through
          case 156: break;
          case 68:
            { return token(yytext(), "PALABRA_RESERVADA:PUBLIC", yyline, yycolumn);
            }
            // fall through
          case 157: break;
          case 69:
            { return token(yytext(), "PALABRA_RESERVADA:RETURN", yyline, yycolumn);
            }
            // fall through
          case 158: break;
          case 70:
            { return token(yytext(), "PALABRA_RESERVADA:STATIC", yyline, yycolumn);
            }
            // fall through
          case 159: break;
          case 71:
            { return token(yytext(), "PALABRA_RESERVADA:SWITCH", yyline, yycolumn);
            }
            // fall through
          case 160: break;
          case 72:
            { return token(yytext(), "PALABRA_RESERVADA:THROWS", yyline, yycolumn);
            }
            // fall through
          case 161: break;
          case 73:
            { return token(yytext(), "PALABRA_RESERVADA:BOOLEAN", yyline, yycolumn);
            }
            // fall through
          case 162: break;
          case 74:
            { return token(yytext(), "PALABRA_RESERVADA:DEFAULT", yyline, yycolumn);
            }
            // fall through
          case 163: break;
          case 75:
            { return token(yytext(), "PALABRA_RESERVADA:EXTENDS", yyline, yycolumn);
            }
            // fall through
          case 164: break;
          case 76:
            { return token(yytext(), "PALABRA_RESERVADA:FINALLY", yyline, yycolumn);
            }
            // fall through
          case 165: break;
          case 77:
            { return token(yytext(), "PALABRA_RESERVADA:PACKAGE", yyline, yycolumn);
            }
            // fall through
          case 166: break;
          case 78:
            { return token(yytext(), "PALABRA_RESERVADA:PRIVATE", yyline, yycolumn);
            }
            // fall through
          case 167: break;
          case 79:
            { return token(yytext(), "PALABRA_RESERVADA:ABSTRACT", yyline, yycolumn);
            }
            // fall through
          case 168: break;
          case 80:
            { return token(yytext(), "PALABRA_RESERVADA:CONTINUE", yyline, yycolumn);
            }
            // fall through
          case 169: break;
          case 81:
            { return token(yytext(), "PALABRA_RESERVADA:STRICTFP", yyline, yycolumn);
            }
            // fall through
          case 170: break;
          case 82:
            { return token(yytext(), "PALABRA_RESERVADA:VOLATILE", yyline, yycolumn);
            }
            // fall through
          case 171: break;
          case 83:
            { return token(yytext(), "PALABRA_RESERVADA:INTERFACE", yyline, yycolumn);
            }
            // fall through
          case 172: break;
          case 84:
            { return token(yytext(), "PALABRA_RESERVADA:PROTECTED", yyline, yycolumn);
            }
            // fall through
          case 173: break;
          case 85:
            { return token(yytext(), "PALABRA_RESERVADA:TRANSIENT", yyline, yycolumn);
            }
            // fall through
          case 174: break;
          case 86:
            { return token(yytext(), "PALABRA_RESERVADA:IMPLEMENTS", yyline, yycolumn);
            }
            // fall through
          case 175: break;
          case 87:
            { return token(yytext(), "PALABRA_RESERVADA:INSTANCEOF", yyline, yycolumn);
            }
            // fall through
          case 176: break;
          case 88:
            { return token(yytext(), "PALABRA_RESERVADA:SYNCHRONIZED", yyline, yycolumn);
            }
            // fall through
          case 177: break;
          case 89:
            { /* Ignorar comentarios de múltiples líneas */
            }
            // fall through
          case 178: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
